language: cpp

before_install:
- sudo apt-get install libopencv-dev
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
- sudo apt-get update
- sudo apt-get install qdbus qmlscene qt5-default qt5-qmake qtbase5-dev-tools qtchooser qtdeclarative5-dev libqt5svg5-dev qttools5-dev qtscript5-dev -y

script:
- cd Application
- qmake -qt=qt5
- make 

compiler:
  - clang
  - gcc

 notifications:
  email: false