sudo: required
dist: trusty

language: cpp

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libopencv-dev
- sudo apt-get install -y qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
- sudo apt-get install -y qt5-default qttools5-dev-tools
- if [ "$CXX" = "g++" ]; then sudo apt-get install -y gcc-4.8 g++-4.8; sudo update-alternatives --remove-all gcc; sudo update-alternatives --remove-all g++; sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20; sudo update-alternatives --config gcc; sudo update-alternatives --config g++; fi
- if [ "$CXX" = "g++" ]; then sudo apt-get install -y clang-3.6 clang++-3.6; fi

script:
- cd Application
- if [ "$CXX" = "clang++" ]; then qmake -qt=qt5 -spec linux-clang ; fi
- if [ "$CXX" != "clang++" ]; then qmake -qt=qt5 ; fi
- make
- make install

compiler:
- clang
- gcc

notifications:
  email: false
