language: cpp

before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install libopencv-dev
- sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
- sudo apt-get install qt5-default qttools5-dev-tools
#- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
#- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
#- sudo apt-get install qdbus qmlscene qt5-default qt5-qmake qtbase5-dev-tools qtchooser qtdeclarative5-dev libqt5svg5-dev qttools5-dev qtscript5-dev -y

script:
- cd Application
- if [ "$CXX" == "clang++" ]; then qmake -qt=qt5 -spec linux-clang++ ; fi
- if [ "$CXX" != "clang++" ]; then qmake -qt=qt5 ; fi
- make

compiler:
- clang
- gcc

notifications:
  email: false