language: cpp

before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq qt5-qmake qtbase5-dev qtgui5-dev
- sudo apt-get install libopencv-dev

script:
- cd Application
- qmake -qt=qt5 -v
- qmake -qt=qt5
- make 

compiler:
  - clang
  - gcc